 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/contas", type: :request do
  # Conta. As you add validations to Conta, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Conta.create! valid_attributes
      get contas_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      conta = Conta.create! valid_attributes
      get conta_url(conta)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_conta_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      conta = Conta.create! valid_attributes
      get edit_conta_url(conta)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Conta" do
        expect {
          post contas_url, params: { conta: valid_attributes }
        }.to change(Conta, :count).by(1)
      end

      it "redirects to the created conta" do
        post contas_url, params: { conta: valid_attributes }
        expect(response).to redirect_to(conta_url(Conta.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Conta" do
        expect {
          post contas_url, params: { conta: invalid_attributes }
        }.to change(Conta, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post contas_url, params: { conta: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested conta" do
        conta = Conta.create! valid_attributes
        patch conta_url(conta), params: { conta: new_attributes }
        conta.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the conta" do
        conta = Conta.create! valid_attributes
        patch conta_url(conta), params: { conta: new_attributes }
        conta.reload
        expect(response).to redirect_to(conta_url(conta))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        conta = Conta.create! valid_attributes
        patch conta_url(conta), params: { conta: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested conta" do
      conta = Conta.create! valid_attributes
      expect {
        delete conta_url(conta)
      }.to change(Conta, :count).by(-1)
    end

    it "redirects to the contas list" do
      conta = Conta.create! valid_attributes
      delete conta_url(conta)
      expect(response).to redirect_to(contas_url)
    end
  end
end
