default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: financeira_nobe_development

test:
  <<: *default
  database: financeira_nobe_test

production:
  <<: *default
  database: financeira_nobe_production
  username: financeira_nobe
  password: <%= ENV['FINANCEIRA_NOBE_DATABASE_PASSWORD'] %>

# ======== SQLITE3 ============
# default: &default
#   adapter: sqlite3
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000

# development:
#   <<: *default
#   database: db/development.sqlite3

# test:
#   <<: *default
#   database: db/test.sqlite3

# production:
#   <<: *default
#   database: db/production.sqlite3
